replicaCount: 1

image:
  repository: IMAGE_REPOSITORY
  tag: IMAGE_TAG
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  host: APP_NAME.hardikdevportal.duckdns.org