name: Application Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "GitHub Repository Url"
        required: true
        type: string

      app_name:
        description: "Application Name"
        required: true
        type: string


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DevPortal Repository
        uses: actions/checkout@v4

      - name: Print Repository URL and Application Name
        run: |
          echo "Repository URL: ${{ inputs.repo_url }}"
          echo "App Name: ${{ inputs.app_name }}"

      - name: Cloning User Repository
        run: |
          git clone ${{ inputs.repo_url }} user-app

      - name: Verify Contents of the Repository
        id: detect-app-type
        run: |

          FRONTEND_ENABLED=false
          BACKEND_ENABLED=false

          ls -la user-app

          if [ -d "user-app/frontend" ]; then
          FRONTEND_ENABLED=true
          fi

          if [ -d "user-app/backend" ]; then
          BACKEND_ENABLED=true
          fi

          echo "frontend_enabled=$FRONTEND_ENABLED" >> $GITHUB_OUTPUT
          echo "backend_enabled=$BACKEND_ENABLED" >> $GITHUB_OUTPUT

          echo "Frontend Enabled = $FRONTEND_ENABLED"
          echo "Backend Enabled = $BACKEND_ENABLED"

      - name: Get Commit SHA
        id: git-sha
        run: |
          cd user-app

          SHA=$(git rev-parse --short HEAD)

          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "Commit SHA: $SHA"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create Frontend Repository, build docker and push to ECR
        id: frontend-image
        env:
          FRONTEND_ENABLED: ${{ steps.detect-app-type.outputs.frontend_enabled }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          if [ "$FRONTEND_ENABLED" = "true" ]; then

          aws ecr describe-repositories \
            --repository-names ${{ inputs.app_name }}-frontend
          || \
          aws ecr create-repository \
            --repository-name ${{ inputs.app_name }}-frontend

          docker build \
            -t $ECR_REGISTRY/${{ inputs.app_name }}-frontend:$IMAGE_TAG \
            ./user-app/frontend
          
          docker push \
            $ECR_REGISTRY/${{ inputs.app_name }}-frontend:$IMAGE_TAG
          
          IMAGE_FRONTEND_REPOSITORY=$ECR_REGISTRY/${{ inputs.app_name }}-frontend
          
          echo "image_frontend_repository=$IMAGE_FRONTEND_REPOSITORY" >> $GITHUB_OUTPUT
          echo "Image Frontend Repository: $IMAGE_FRONTEND_REPOSITORY "

          fi

      - name: Create Backend Repository, build image and push to ECR
        id: backend-image
        env:
          BACKEND_ENABLED: ${{ steps.detect-app-type.outputs.backend_enabled }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          if [ "$BACKEND_ENABLED" = "true" ]; then
        
          aws ecr describe-repositories \
            --repository-names ${{ inputs.app_name }}-backend \
          || \
          aws ecr create-repository \
            --repository-name ${{ inputs.app_name }}-backend

          docker build \
            -t $ECR_REGISTRY/${{ inputs.app_name }}-backend:$IMAGE_TAG \
            ./user-app/backend

          docker push \
            $ECR_REGISTRY/${{ inputs.app_name }}-backend:$IMAGE_TAG

          IMAGE_BACKEND_REPOSITORY=$ECR_REGISTRY/${{ inputs.app_name }}-backend

          echo "image_backend_repository=$IMAGE_BACKEND_REPOSITORY" >> $GITHUB_OUTPUT
          echo "Image Backend Repository: $IMAGE_BACKEND_REPOSITORY"

          fi


      - name: Print Final Image Information
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          echo "===================================="
          echo "Image Successfully Pushed"
          echo "===================================="
          echo "Frontend Repository Name: ${{ steps.frontend-image.outputs.image_frontend_repository }}"
          echo "Backend Repository Name: ${{ steps.backend-image.outputs.image_backend_repository }}"
          echo "Tag: $IMAGE_TAG"
          echo "Image:"
          echo "$ECR_REGISTRY/${{ inputs.app_name }}-frontend:$IMAGE_TAG"
          echo "$ECR_REGISTRY/${{ inputs.app_name }}-backend:$IMAGE_TAG"

      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/HardikYadav99/devportal-gitops.git

      - name: Create Application Folder
        run: |
          mkdir -p \
            devportal-gitops/source-app/${{ inputs.app_name }}

      
      - name: Copy Templates
        run: |

          echo "checking the current directory"
          ls -l
          pwd

          cp templates/values-template.yaml \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          cp templates/metadata-template.json \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json

          cp templates/application-template.yaml \
            devportal-gitops/argocd-apps/${{ inputs.app_name }}-app.yaml

      - name: Replace Placeholders
        env:
          IMAGE_FRONTEND_REPOSITORY: ${{ steps.frontend-image.outputs.image_frontend_repository }}
          IMAGE_BACKEND_REPOSITORY: ${{ steps.backend-image.outputs.image_backend_repository }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          sed -i \
            "s|IMAGE_FRONTEND_REPOSITORY|$IMAGE_FRONTEND_REPOSITORY|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml
          
          sed -i \
            "s|IMAGE_BACKEND_REPOSITORY|$IMAGE_BACKEND_REPOSITORY|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          sed -i \
            "s|IMAGE_TAG|$IMAGE_TAG|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          sed -i \
            "s|APP_NAME|${{ inputs.app_name }}|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          sed -i \
            "s|FRONTEND_ENABLED|${{ steps.detect-app-type.outputs.frontend_enabled }}|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml
          
          sed -i \
            "s|BACKEND_ENABLED|${{ steps.detect-app-type.outputs.backend_enabled }}|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml
          
          sed -i \
            "s|APP_NAME|${{ inputs.app_name }}|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json

          sed -i \
            "s|IMAGE_FRONTEND_REPOSITORY|$IMAGE_FRONTEND_REPOSITORY|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json

          sed -i \
            "s|IMAGE_BACKEND_REPOSITORY|$IMAGE_BACKEND_REPOSITORY|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json

          sed -i \
            "s|CREATED_AT|$CREATED_AT|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json
          
          sed -i \
            "s|REPO_URL|${{ inputs.repo_url }}|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json


          sed -i \
            "s|APP_NAME|${{ inputs.app_name }}|g" \
            devportal-gitops/argocd-apps/${{ inputs.app_name }}-app.yaml


      - name: Print Generated Values File
        run: |
          echo "================================="
          echo "Generated values.yaml"
          echo "================================="
          cat \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

      - name: Commit and Push Changes
        run: |
          cd devportal-gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add \
            source-app/${{ inputs.app_name }}/values.yaml \
            source-app/${{ inputs.app_name }}/metadata.json


          git commit -m "Deploy ${{ inputs.app_name }}:${{ steps.git-sha.outputs.sha }}" || exit 0

          git push