name: Application Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "GitHub Repository Url"
        required: true
        type: string

      app_name:
        description: "Application Name"
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Print Repository URL and Application Name
        run: |
          echo "Repository URL: ${{ inputs.repo_url }}"
          echo "App Name: ${{ inputs.app_name }}"

      - name: Cloning User Repository
        run: |
          git clone ${{ inputs.repo_url }} user-app

      - name: Verify Contents of the Repository
        run: |
          ls -la user-app

      - name: Get Commit SHA
        id: git-sha
        run: |
          cd user-app

          SHA=$(git rev-parse --short HEAD)

          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "Commit SHA: $SHA"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check or Create Repository
        run: |
          aws ecr describe-repositories \
            --repository-names ${{ inputs.app_name }} \
          || \
          aws ecr create-repository \
            --repository-name ${{ inputs.app_name }}

      - name: Build Docker Image
        env:
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          docker build \
            -t ${{ inputs.app_name }}:$IMAGE_TAG \
            ./user-app

      - name: Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          docker tag \
            ${{ inputs.app_name }}:$IMAGE_TAG \
            $ECR_REGISTRY/${{ inputs.app_name }}:$IMAGE_TAG

          docker push \
            $ECR_REGISTRY/${{ inputs.app_name }}:$IMAGE_TAG

      - name: Build Image Repository String
        id: image-info
        env:
          ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          IMAGE_REPOSITORY="$ECR_REPOSITORY/${{ inputs.app_name }}"

          echo "image_repository=$IMAGE_REPOSITORY" >> $GITHUB_OUTPUT
          echo "Image Repository = $IMAGE_REPOSITORY"

      - name: Print Final Image Information
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          echo "===================================="
          echo "Image Successfully Pushed"
          echo "===================================="
          echo "Repository Name: ${{ inputs.app_name }}"
          echo "Tag: $IMAGE_TAG"
          echo "Image:"
          echo "$ECR_REGISTRY/${{ inputs.app_name }}:$IMAGE_TAG"

      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/HardikYadav99/devportal-gitops.git

      - name: Create Application Folder
        run: |
          mkdir -p \
            devportal-gitops/source-app/${{ inputs.app_name }}

      - name: Debugging the Current repository issue 
        run: |
          echo "Current Repository"
          pwd

          echo ""
          echo "Print Everything in the current "
          ls -la

          echo ""
          echo "Searching for current template"
          find . -name "*template*"

          echo ""
          echo "Searching for the YAML "
          find . -name "*yaml"

      - name: Copy Templates
        run: |

          echo "checking the current directory"
          ls -l
          pwd

          cp templates/values-template.yaml \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          cp templates/metadata-template.json \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json

          cp templates/application-template.yaml \
            devportal-gitops/argocd-apps/${{ inputs.app_name }}-app.yaml

      - name: Replace Placeholders
        env:
          IMAGE_REPOSITORY: ${{ steps.image-info.outputs.image_repository }}
          IMAGE_TAG: ${{ steps.git-sha.outputs.sha }}
        run: |
          CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          sed -i \
            "s|IMAGE_REPOSITORY|$IMAGE_REPOSITORY|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          sed -i \
            "s|IMAGE_TAG|$IMAGE_TAG|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          sed -i \
            "s|APP_NAME|${{ inputs.app_name }}|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

          sed -i \
            "s|CREATED_AT|$CREATED_AT|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json

          sed -i \
            "s|APP_NAME|${{ inputs.app_name }}|g" \
            devportal-gitops/source-app/${{ inputs.app_name }}/metadata.json

          sed -i \
            "s|APP_NAME|${{ inputs.app_name }}|g" \
            devportal-gitops/argocd-apps/${{ inputs.app_name }}-app.yaml

      - name: Print Generated Values File
        run: |
          echo "================================="
          echo "Generated values.yaml"
          echo "================================="
          cat \
            devportal-gitops/source-app/${{ inputs.app_name }}/values.yaml

      - name: Commit and Push Changes
        run: |
          cd devportal-gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Deploy ${{ inputs.app_name }}:${{ steps.git-sha.outputs.sha }}" || exit 0

          git push