name: Deletion Application Pipeline

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name from the user'
        required: true
        type: string

permissions:
  contents: write

jobs:
  delete-applications:
    runs-on: ubuntu-latest

    steps:
      - name: Configure kubectl access
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          kubectl get application -n argocd

      - name: Cloning the Gitops repository
        run: |
          git clone "https://x-access-token:${{ secrets.GH_PAT }}@github.com/HardikYadav99/devportal-gitops.git"

      - name: Deleting Argocd application file and pushing to github
        run: |
          rm -f devportal-gitops/argocd-apps/${{ inputs.app_name }}-app.yaml 
          cd devportal-gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deleted Argocd-apps/${{ inputs.app_name }}" || true 
          git push origin main
    
      - name: Wait for Argocd to detect change
        run: |
          sleep 30

      - name: Force ArgoCD to refresh immediately
        run: |
          kubectl patch application ${{ inputs.app_name }} -n argocd --type merge -p '{"metadata":{"annotations":{"argocd.argoproj.io/refresh":"hard"}}}'
          sleep 10

      - name: Deleting Kubernetes App related resources
        run: |
          kubectl delete deployment -n default -l app=${{ inputs.app_name }} --ignore-not-found
          kubectl delete service -n default -l app=${{ inputs.app_name }} --ignore-not-found
          kubectl delete ingress -n default -l app=${{ inputs.app_name }} --ignore-not-found

          kubectl delete secret ${{ inputs.app_name }}-tls \
            -n default \
            --ignore-not-found
      
      - name: Deleting Source Application 
        run: |
          rm -rf devportal-gitops/source-app/${{ inputs.app_name }}

      - name: Push source files app deletion to github 
        run: |
          cd devportal-gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deleted source-app/${{ inputs.app_name }} successfully" || true
          git push origin main

      - name: Check the remaining files 
        run: |
          echo "Remaining files in Argocd-apps folder"
          ls -la devportal-gitops/argocd-apps
          echo ""
          echo "Remaining Files in Source-App folder"
          ls -la devportal-gitops/source-app