name: Delete Application Pipeline 

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Application Name"
        required: true
        type: string
permissions:
  contents: write

jobs:
  delete-application:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning GitOps Repository
        run: |
          git clone "https://x-access-token:${{ secrets.GH_PAT }}@github.com/HardikYadav99/devportal-gitops.git"

      - name: Delete ArgoCD application 
        run: |

          rm -f \
            devportal-gitops/argocd-apps/${{ inputs.app_name }}-app.yaml

      - name: Commit ArgoCd Application deletion 
        run: |
          cd devportal-gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit \
            -m "Deleted ArgoCd ${{ inputs.app_name }}-app.yaml" || true
          git push
          